# Schema for SDSS table subset
filters: {complevel: 5, complib: blosc}
schema:
  common:
    primary_key: objID
    spatial_keys: [ra, dec]
    columns:
    - [run, u4]
    - [rerun, a3]
    - [camcol, u4]
    - [field, u4]
    - [objID, u4]
    - [obj_type, u4]
    - [obj_flags, u4]
    - [obj_flags2, u4]
    - [zhedflag, i2]
    - [obj_rowc, f4]
    - [rowv, f4]
    - [rowverr, f4]
    - [colv, f4]
    - [colverr, f4]
    - [colc, f4]
    - [flags, u4]
    - [flags2, u4]
    - [ra, f8]
    - [dec, f8]
  photometry:
    columns:
    - [skyflux, f4]
    - [psfflux, f4]
    - [psfflux_ivar, f4]
    - [modelflux, f4]
    - [modelflux_ivar, f4]
    - [extinction, f4]
    - [aperflux6, f4]
  image:
    columns:
    - [psp_status, u4]
    - [psf_fwhm, f4]
    - [thing_ID, u4]
    - [ifield, u4]
    - [balkan_id, u4]
    - [ndetect, i2]
    - [calib_status, i2]
    - [nmgypercount, f4]
  tmass:
    columns:
    - [tmass_j, f4]
    - [tmass_j_ivar, f4]
    - [tmass_h, f4]
    - [tmass_h_ivar, f4]
    - [tmass_k, f4]
    - [tmass_k_ivar, f4]
    - [tmass_ph_qual, a3]
    - [tmass_rd_flg, i2]
    - [tmass_bl_flg, i2]
    - [tmass_cc_flg, a3]
    - [tmass_gal_contam, u1]
    - [tmass_mp_flg, u1]
    - [tmass_jdate, f8]
    - [tmass_matchdist, f4]
    - [tmass_nmatch, i4]